### ISSUE TITLE
timeouts and reconnects

### ISSUE THREAD

**Issue by j0sh** [ostinelli/apnotic#35] opened 2016-10-13 14:11 UTC
Doing some light testing with this gem and one thing I'm seeing is that after a certain length of time, connections to APNS time out, regardless of what the timeout parameter is set to. (I think the default timeout is 30s, while it takes ~15 minutes to time out here. Here is what the backtrace fails with: [2].

Are there any best practices for keeping the connection alive over a sporadically used connection? And if the connection does fail eventually, will the HTTP2 client take care of reconnects in pooled mode, as the ConnectionPool library says it should [1]? Testing this scenario right now but figured I'd ask here as well. Using dev servers, for what it's worth.

[1] https://github.com/mperham/connection_pool
[2] https://gist.github.com/j0sh/a215eebb8f1f0cc4d6f6270bc02df352

**Comment by ostinelli** [comment] 2016-10-13 15:28
> Doing some light testing with this gem and one thing I'm seeing is that after a certain length of time, connections to APNS time out, regardless of what the `timeout` parameter is set to. (I think the default timeout is 30s, while it takes ~15 minutes to time out here.

Hi @j0sh, `timeout` as option in a sync push is the amount of time after which a `nil` response is sent back. This doesn't necessarily mean that the TCP socket is closed; it just means that the response did not come within the specified `timeout`. We could think of forcing a disconnect in case a timeout occurs on a single response, but it is necessary to look into the implications of that.

Hence, can you please clarify with the ~15 minutes you're referring to? Since the last pusH? From your gist I don't see it.

Also, note that if you are using Apple development servers it is to be expected that they eject you after some inactivity. This happens way less in production.

> Are there any best practices for keeping the connection alive over a sporadically used connection? 

Connections are persistent, so you don't need to do anything. 

> And if the connection does fail eventually, will the HTTP2 client take care of reconnects in pooled mode, as the ConnectionPool library says it should [1]? Testing this scenario right now but figured I'd ask here as well. Using dev servers, for what it's worth.

From the README:

> In case that errors are encountered, Apnotic will repair the underlying connection but will not retry the requests that have failed. For this reason, it is recommended to use a queue engine that will retry unsuccessful pushes.

**Comment by j0sh** [comment] 2016-10-13 16:08
> Hence, can you please clarify with the ~15 minutes you're referring to? Since the last push?

15 minutes after the push attempt is made (after some period of idleness, say overnight), it finally gives up and crashes with that exception given in the backtrace. So the timeout is not kicking in for some reason.

Forgot to mention these are async pushes though. Are the timeout semantics different for sync/async pushes?

> In case that errors are encountered, Apnotic will repair the underlying connection but will not retry the requests that have failed. 

Not what I'm seeing here -- this is a hard crash. Although maybe just a case of handling that one exception from openssl, and reopening the connection from there.

**Comment by ostinelli** [comment] 2016-10-15 12:45
> 15 minutes after the push request is made (after some period of idleness, say overnight), it finally gives up and crashes with that exception given in the backtrace. So the timeout is not kicking in for some reason.
>
> Forgot to mention these are async pushes though. Are the timeout semantics different for sync/async pushes?

Yes, there is no timeout handling in async pushes. I should clarify that in the README, it is only clarified in [NetHttp2's README](https://github.com/ostinelli/net-http2/blob/0.14.0/README.md#non-blocking-calls).

> Not what I'm seeing here -- this is a hard crash. Although maybe just a case of handling that one exception from openssl, and reopening the connection from there.

I think you might be missing how this works, and why Sidekiq / Rescue are recommended. Apnotic _will_ raise an error when an error (like the one you're seeing) happens on the connection. This is _by design_, so that the job manager (Sidekiq, Resque,...) can retry the job. When that happens, Apnotic repairs the underlying connection, so everything just works.

Hope this clears up.

**Comment by idyll** [comment] 2016-10-20 18:59
I've seen issues with Sidekiq threads hanging after about 24 hours of use.
I am pushing about 30,000 messages an hour over 2 sidekiq workers...

Wondering if this is related?

**Comment by idyll** [comment] 2016-10-21 11:07
It was my sidekiq version I think. I will be able to confirm in 24 hours.

**Comment by idyll** [comment] 2016-10-26 00:34
so it looks like it is memory. the thing is, I pass my push token and message into sidekiq. so there has to be a memory leak somewhere. the process isn't doing anything else.

**Comment by ostinelli** [comment] 2016-10-27 11:56
Hello @idyll,
I'm sorry I can't see any followable inputs in these 3 comments. I'm not even sure why you think these are related to @j0sh original issue.

Hence, closing this issue in favour of #36.

If, for some reason, you believe that there's a memory leak somewhere (I can't read why you'd think so) please open another issue on how to reproduce.

**Closed by ostinelli** 2016-10-27 11:56 UTC
