### ISSUE TITLE
Connection reset by peer after some period of time when using a connection pool in Sidekiq

### ISSUE THREAD

**Issue by eebs** [ostinelli/apnotic#17] opened 2016-06-24 21:17 UTC
Hello, I'm running into an issue where my Sidekiq process is crashing after some period of time when attempting to use a connection from a pool. I'm not entirely sure if it's an issue with Apnotic, with how I'm managing the connection pool, or with my own code being thread safe. I would appreciate any help, or maybe even pointing in the right direction for how to determine exactly what the issue is.

The stack trace is
```
2016-06-24T20:19:17.083Z 11526 TID-ovumo5ako Deliveries::IosDeliveryWorker JID-f2ac3377caf5893f8a8941cb BID-hZm_HvyLaQMLZw INFO: start
2016-06-24T20:19:17.084Z 11526 TID-ovuna5ck0 Deliveries::IosDeliveryWorker JID-a45d7efd9590715caccd576f BID-hZm_HvyLaQMLZw INFO: start
Connection reset by peer
/Users/eebs/.rubies/ruby-2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock'
/Users/eebs/.rubies/ruby-2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in `read_nonblock'
/Users/eebs/.gem/ruby/2.3.1/gems/net-http2-0.11.1/lib/net-http2/client.rb:90:in `block in socket_loop'
/Users/eebs/.gem/ruby/2.3.1/gems/net-http2-0.11.1/lib/net-http2/client.rb:87:in `loop'
/Users/eebs/.gem/ruby/2.3.1/gems/net-http2-0.11.1/lib/net-http2/client.rb:87:in `socket_loop'
/Users/eebs/.gem/ruby/2.3.1/gems/net-http2-0.11.1/lib/net-http2/client.rb:71:in `block (2 levels) in ensure_open'
```
This is happening after I:
* Start Sidekiq
* Enqueue a few notifications
* Wait 30-60 minutes
* Try and send a few more notifications

This is crashing the entire sidekiq process, not just a single job.

Here is a paired down version of the code I'm running with hopefully all the important bits left in:

---

**ios_delivery_worker.rb**

Each `IosDeliveryWorker` is responsible for sending one push notification to the target `token` belonging to the given native app identified by `app_id`, and recording the response. It retrieves a native app specific `Apnotic::ConnectionPool` from the `PoolManager::Ios` class stored in the `POOLS` constant. It uses the connection pool to send the notification as suggested in the Readme.

```ruby
class IosDeliveryWorker
  include Sidekiq::Worker
  sidekiq_options queue: 'push', :backtrace => true

  attr_reader :token, :app_id, :payload

  def perform(token, app_id, paylod)
    @token   = token
    @app_id  = app_id
    @payload = payload

    response = publish_message
    update_delivery(response)
  end

  POOLS = PoolManager::Ios.new

  private

  def publish_message
    POOLS.for(app_id) do |pool|
      pool.with do |connection|
        notification = Apnotic::Notification.new(token)
        # ... assign payload, etc
        connection.push(notification)
      end
    end
  end

  def update_delivery(response)
    # ... update response, etc
  end
end
```

**pool_manager/ios.rb**

The `PoolManager::Ios` class is used to retrieve an `Apnotic::ConnectionPool` for a given native application. It uses a hash to store the connection pools, keyed by the native application's ID. Access to the hash is wrapped in a Mutex to protect against multiple Sidekiq threads from accessing the hash at the same time, and potentially corrupting it. This seems to work in practice, as I can see that only one connection pool is created (by logging when creating the connection pool), but concurrent processing is an area in which I am less familiar. Do you think something I'm doing while managing the pools is causing a problem?

```ruby
module PoolManager
  class Ios

    attr_reader :pool_size

    def initialize(pool_size=5)
      @store = {}
      @mutex = Mutex.new
      @pool_size = pool_size
    end

    def for(id)
      @mutex.synchronize do
        pool = @store[id]

        unless pool
          app = IosApp.find(id)
          push_url = app.production? ? Apnotic::APPLE_PRODUCTION_SERVER_URL : Apnotic::APPLE_DEVELOPMENT_SERVER_URL

          pool = Apnotic::ConnectionPool.new({
            url: push_url,
            cert_path: Paperclip.io_adapters.for(app.certificate),
            cert_pass: app.certificate_password
          }, size: pool_size)
          @store[id] = pool
        end

        yield pool
      end
    end
  end
end
```
---

Will the connections in the pool become unusable after some period of time? It seems they are closing or being reset, and then crashing the Sidekiq process when they are used again. I see that there is a `close` method on `Apnotic::Connection`, but if I close each connection after pushing the notification, I see a tremendous decrease in throughput (from ~200ms per job to ~1600ms per job).

I'm not entirely sure what the issue is, but I believe that the connections in the pool are getting closed or disconnected, and the error happens when they are attempted to be used again. If this is the case, it would be great if the connection pool would be able to recover from closed connections rather than crashing.

Sorry for the overload of information, but I hope I have given you enough context to help me find the issue. If there is anything else I can provide, please let me know. I would also happily submit a PR if I knew what the issue was and I was able to fix it.

Thanks for the great library!

**Comment by ostinelli** [comment] 2016-06-27 14:33
hi @eebas, unfortunately it would take quite a while for me to go through your implementations. Try to reproduce an isolated bug and see if this relates to Apnotic or Sidekiq in the first place.

**Comment by eebs** [comment] 2016-06-27 14:38
After some further testing this weekend, it appears to be an issue with the connections either timing out or resetting.

I changed my implementation to return a new connection pool if it had not been used for 5 minutes, and now everything is working fine.

This indicates to me that the connections in the Apnotic connection pool are becoming unusable after some period of time. The [APNs documentation](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW14) mentions that the APNs servers may terminate the connection after some period of time by sending the `GOAWAY` frame. Could it be that this is not being handled?

**Comment by eebs** [comment] 2016-06-27 14:40
If I have some extra time I will try to create a reduced test case that consistently exhibits this behavior.

**Comment by ostinelli** [comment] 2016-06-27 15:50
> After some further testing this weekend, it appears to be an issue with the connections either timing out or resetting.

We use Apnotic in production in both very intensive and in extremely lightweight environments (less than 10 pushes per day), so I would expect to experience something similar if this was the issue. Also, this doesn't explain why you're seeing Sidekiq crashes.

> I changed my implementation to return a new connection pool if it had not been used for 5 minutes, and now everything is working fine.

This is probably just hiding what the real problem is.

> If I have some extra time I will try to create a reduced test case that consistently exhibits this behavior.

That would be great.

**Comment by ostinelli** [comment] 2016-06-27 15:55
BTW why do you:

```ruby
yield pool
```

**Comment by eebs** [comment] 2016-06-27 15:57
> BTW why do you:
  ```
yield pool
  ```

I suppose I don't need to. I could simply return the pool and use it without a block.

**Comment by ostinelli** [comment] 2016-06-27 15:58
BTW why do you:

```ruby
yield pool
```

**Comment by ostinelli** [comment] 2016-06-27 16:01
Oops some connectivity problems here, I though my post didn't get through in the first place. :)

Well, my point is: you're yielding the block _inside of your mutex_ so your `connection.push(notification)` happens inside of your mutex too. Is this what you intended to do?

I would refactor to avoid using a mutex like this, and see if this solves your issues.

**Comment by eebs** [comment] 2016-06-27 16:06
Oh, of course 😳. Will update this afternoon.

**Comment by eebs** [comment] 2016-06-27 20:13
Even after fixing the `yield` issue, I'm still getting `Errno::ECONNRESET: Connection reset by peer` after waiting ~1 hour between pushes.

I was able to recreate a similar, issue using the following:

```ruby
require 'apnotic'

# create a persistent connection
connection = Apnotic::Connection.development(cert_path: "apns_certificate.p12", cert_pass: "mypassword")

# create a notification for a specific device token
token = "da0e95a7dfe0e9d78bcccaf6a94b239e3c218f0299466794819c4f934c3a20d8"

notification       = Apnotic::Notification.new(token)
notification.alert = "Notification from Apnotic!"
notification.topic = 'mytopichere'

# send (this is a blocking call)
response = connection.push(notification)

sleep(3660)

response = connection.push(notification)
raise response.inspect
```

If I run this without the call to `sleep` I get two notifications, and it raises a good response:

```
$ ruby apnotic.rb 
apnotic.rb:18:in `<main>': #<Apnotic::Response:0x007fcd9b8e8b48 @headers={":status"=>"200", "apns-id"=>"47a9c34b-74eb-4df0-8a3d-3b6f76579643"}, @body=""> (RuntimeError)
```

However, if I sleep for over an hour, the `response` is  `nil`.

```
$ ruby apnotic.rb 
apnotic.rb:20:in `<main>': nil (RuntimeError)
```

I haven't tried to reduce this to the minimum time needed to fail, I will try running this test with various sleep times.

**Comment by eebs** [comment] 2016-06-27 20:29
Looking more closely, could this [`abort_on_exception`](https://github.com/ostinelli/net-http2/blob/master/lib/net-http2/client.rb#L79) be the issue? "When set to true, all threads (including the main program) will abort if an exception is raised in this thr." Sounds like this is what is causing my Sidekiq process to raise an exception.

**Comment by ostinelli** [comment] 2016-06-28 09:14
These are two unrelated issues, so let's keep track of them individually :)

> Looking more closely, could this abort_on_exception be an issue?

I will code and push tonight changes to [NetHttp2](https://github.com/ostinelli/net-http2) that will get rid of this issue.

> However, if I sleep for over an hour, the `response` is `nil`.

Response is `nil` whenever a call timed out. Please keep me updated on your tests.

**Comment by ostinelli** [comment] 2016-06-28 21:48
> I will code and push tonight changes to NetHttp2 that will get rid of this potential issue.

This is now in.

**Comment by eebs** [comment] 2016-06-29 15:39
I've been doing some more testing, and I still am seeing connection resets after ~1 hour of inactivity.

Using TracePoint, I'm quite clearly able to see the excepting being raised in `NetHttp2::Client`'s `socket_loop`:

```
#<Errno::ECONNRESET: Connection reset by peer>
/Users/eebs/.rubies/ruby-2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock'
/Users/eebs/.rubies/ruby-2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in `read_nonblock'
/Users/eebs/.gem/ruby/2.3.1/gems/net-http2-0.11.1/lib/net-http2/client.rb:90:in `block in socket_loop'
/Users/eebs/.gem/ruby/2.3.1/gems/net-http2-0.11.1/lib/net-http2/client.rb:87:in `loop'
/Users/eebs/.gem/ruby/2.3.1/gems/net-http2-0.11.1/lib/net-http2/client.rb:87:in `socket_loop'
/Users/eebs/.gem/ruby/2.3.1/gems/net-http2-0.11.1/lib/net-http2/client.rb:71:in `block (2 levels) in ensure_open'
```

Looking at the code, I see no attempts to re-establish the connection if an `Errno::ECONNRESET` is thrown when attempting to read from the socket. My understanding is that when the `Errno::ECONNRESET` is thrown, it is not caught and causes the `@socket_thread` to stop running, meaning no data is received. With the new changes the exception will be raised in the main thread (I haven't had a chance to test the new behavior yet).

I suppose my question is, how are you handling connection resets in your production environment? Are you closing the connection after you finish sending messages, and so you're not running into this issue? I am not closing the connection, as I don't have a reliable way to close the connection after the batch of notifications finish sending.

Thanks again for your help.

**Comment by eebs** [comment] 2016-06-29 19:24
Quick update. With the change from `abort_on_exception` to `Thread.main.raise e` the behavior is the same.

The simple script still fails with `Connection reset by peer`, and the main Sidekiq process also raises this exception.

**Comment by ostinelli** [comment] 2016-06-30 17:25
> Looking at the code, I see no attempts to re-establish the connection if an `Errno::ECONNRESET` is thrown when attempting to read from the socket. My understanding is that when the `Errno::ECONNRESET` is thrown, it is not caught and causes the `@socket_thread` to stop running, meaning no data is received.
> [...]
> I suppose my question is, how are you handling connection resets in your production environment?

Let me clarify one thing regarding this and the overall issue here.

Apnotic _will_ raise an error if anything goes wrong in the socket. This is intended behavior. The library does not manage reconnection attempts, because that's exactly what Sidekiq / Resque etc are for. That's why Apnotic raises an error: so that Sidekiq / Resque can retry the same job later on. Therefore, you are indeed right in your understanding: there will be no attempts to re-establish a connection.

So: it's ok to receive an `Errno::ECONNRESET` error (even though for some reason I've never seen one in production), as long as obviously Sidekiq restarts the job.

Regarding this: using `Thread.main.raise` might not be desirable because the main thread may actually be the main Sidekiq supervisor process itself. I'm not familiar with Sidekiq's implementation (does it spawn threads for a job? does it run in the main thread?), so I've adjusted NetHttp2 to raise an error in the _parent_ thread instead (whatever it may be). This fix (https://github.com/ostinelli/net-http2/commit/90d8872716354e093136ec2cda521c7ff880c4f8) is already released in NetHttp2 v0.12.1.

**Comment by eebs** [comment] 2016-06-30 17:39
Okay, this makes a lot more sense. I was under the impression that somehow the connection should repair even if the socket had been reset by the remote server.

Sidekiq does spawn threads for a job. However, because the connection pool is assigned to a constant in the job class, the thread that creates that constant is the main Sidekiq process thread. This is why my Sidekiq process died, and not just one of the jobs that encountered the exception.

I will test again with the new code, but my guess is that even if it just fails the retry-able job, because the socket for that connection is unusable, the jobs will fail continuously.

I'm not sure how I might rescue from an unusable connection. I don't want to take up any more of your time with something that is not an issue with your library, but do you have any suggestions for how I might either repair the connection or reset the connection pool when the reset happens? I presume your architecture is significantly different in your production environment, as it seems your connections do not stay open after you are finished sending a batch of notifications.

I may have to continue returning a new connection pool if it hasn't been used in some time if I'm unable to find another solution.

Do you think the example in the Readme should be updated, as anyone using Sidekiq and following the Readme could potentially run into this issue.

Thank you very much for your time and effort helping me track this down, I do sincerely appreciate it.

**Comment by ostinelli** [comment] 2016-07-07 13:41
@eebs, no worries and actually thank you for your input. I'm currently in vacation - hence the delayed responses.

Given that I want to keep raising errors so that Sidekiq can retry failed jobs, did you experiment more? Please keep me updated as I will folkow up when I get back and free some time.

**Comment by ostinelli** [comment] 2016-07-15 15:59
@eebs, no worries and actually thank you for your input. I'm currently in vacation - hence the delayed responses.

Not sure if I follow your thoughts. Let me paste here a simplified version of the Sidekiq example in the README file:

```ruby
require 'apnotic'

class MyWorker
  include Sidekiq::Worker

  sidekiq_options queue: :push_notifications

  APNOTIC_POOL = Apnotic::ConnectionPool.new({
    cert_path: Rails.root.join("config", "certs", "apns_certificate.pem"),
    cert_pass: "mypass"
  }, size: 5)

  def perform(token)
    APNOTIC_POOL.with do |connection|
      notification       = Apnotic::Notification.new(token)
      notification.alert = "Hello from Apnotic!"

      connection.push(notification)
    end
  end
end
```

This is my current understanding of how this works jointly with Sidekiq.

- A connection pool `APNOTIC_POOL` is created at main thread level, on the class `MyWorker`.
- Sidekiq creates an instance of this worker, and then calls `perform` on it, while trapping errors (with or without threads, it doesn't really matter as long as errors are trapped).
- When an error happens during the worker's `perform` call, the job will not be removed from the queue and therefore retried by Sidekiq.
- On the next try, the connection taken from the pool will heal itself because `ensure_open` reopens it (see [here](https://github.com/ostinelli/net-http2/blob/0.12.1/lib/net-http2/client.rb#L25) and [here](https://github.com/ostinelli/net-http2/blob/0.12.1/lib/net-http2/client.rb#L30)).

You can also try this manually.

 - Use only `size: 1` for your pool:

```ruby
  APNOTIC_POOL = Apnotic::ConnectionPool.new({
    cert_path: Rails.root.join("config", "certs", "apns_certificate.pem"),
    cert_pass: "mypass"
  }, size: 1)
```
 - Modify the `perform` method to raise an error if a special parameter is passed, for instance the boolean `false`:

```ruby
def perform(token)
  raise "test error" unless token
  APNOTIC_POOL.with do |connection|
    [...]
```
 - Call the worker once correctly from your rails console: `MyWorker.perform_async("fc51568bd094a..42b781af1e34fbc")`, and see that you receive the push.
 - Call the worker once to raise the error: `MyWorker.perform_async("false")`, and see the error generated by Sidekiq:

  ```
17:48:32 worker.1 | /Users/roberto/workspace/myapp/app/workers/my_worker.rb:18:in `perform'
17:48:32 worker.1 | /Users/roberto/.rvm/gems/ruby-2.3.1@myapp/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:152:in `execute_job'
17:48:32 worker.1 | /Users/roberto/.rvm/gems/ruby-2.3.1@myapp/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'
  ```

 - Call the worker again correctly: `MyWorker.perform_async("fc51568bd094a..42b781af1e34fbc")`, and see that you receive the push.

Does this clarifies it for you? Any doubts or misinterpretations on my side?

**Comment by ostinelli** [comment] 2016-08-20 19:50
No further activity, closing.

**Closed by ostinelli** 2016-08-20 19:50 UTC

**Comment by eebs** [comment] 2016-08-20 19:53
Hi Roberto,

Sorry for the lack of follow up. I hope to be able to dig into this further some time in the future. Thanks for all your help.

**Comment by ostinelli** [comment] 2016-08-20 23:01
No worries.

**Comment by taras-viiatyk-yalantis** [comment] 2024-05-21 08:50
Hi @eebs !
I'm facing the same issue. Do you remember how you solved it?

**Comment by eebs** [comment] 2024-05-22 15:31
@taras-viiatyk-yalantis I left the company where we were using Apnotic some time ago, but IIRC we were tracking the last time a notification was successfully sent, and re-establishing the connection if no notifications had been sent recently (I think we used 5 minutes).
